name = "hassaudit"
compatibility_date = "2026-05-16"
main = "src/worker.js"
assets = { directory = "./docs" }

kv_namespaces = [
  { binding = "AUDIT_CACHE", id = "b74dfb9fdad243b785492d940b1bd2da" }
]
